-- ACP Intelligence™ — Beta Feedback #001 (Sunday next-week preview).
--
-- A user planning their week on Sunday needs the coming week's plan available
-- for review and advance fulfilment/booking BEFORE Monday. The plan is
-- generated by the unchanged weekly-adaptation path, but until its week
-- actually begins it must not become the user's "current" plan.
--
-- fitness_plans.status was ('active', 'superseded'). We add ONE value,
-- 'scheduled', for a plan prepared ahead of its week_start_date. This keeps
-- the "exactly one active plan per user" invariant intact (the onboarding
-- route's `.eq('status','active').maybeSingle()` would error on two active
-- rows), while still storing the prepared plan in the canonical history
-- table rather than a parallel structure. When the scheduled plan's week
-- begins, the weekly-adaptation route promotes it: status → 'active', the
-- previous plan → 'superseded', and fitness_profile.ai_assessment is updated.
--
-- Additive and non-destructive: no existing row changes, same DROP/ADD CHECK
-- pattern as 20260828000021 (coaching_memory) and 20260830000001.

ALTER TABLE public.fitness_plans DROP CONSTRAINT IF EXISTS fitness_plans_status_check;
ALTER TABLE public.fitness_plans ADD CONSTRAINT fitness_plans_status_check
  CHECK (status IN ('active', 'superseded', 'scheduled'));
