import { StyleSheet, View, ActivityIndicator, TouchableOpacity } from 'react-native';
import { ThemedText } from '@/components/themed-text';
import { useLocalSearchParams, useRouter, Stack } from 'expo-router';
import { palette, radii } from '@/constants/theme';
import { useEffect, useState, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { authService } from '@/services/auth';
import { useAuthModal } from '@/contexts/auth-modal-context';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

interface ResolvedInvite {
  community_id: string; name: string; slug: string | null; community_type: 'open' | 'approval_required';
}

export default function CommunityJoinScreen() {
  const { token } = useLocalSearchParams<{ slug: string; token: string }>();
  const router = useRouter();
  const { showAuthModal } = useAuthModal();

  const [invite, setInvite] = useState<ResolvedInvite | null | undefined>(undefined);
  const [status, setStatus] = useState<'resolving' | 'joining' | 'joined' | 'error'>('resolving');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const join = useCallback(async (inv: ResolvedInvite) => {
    const session = await authService.getSession();
    const uid = session?.user.id;
    if (!uid) {
      showAuthModal(() => join(inv), { defaultTab: 'signup' });
      return;
    }
    setStatus('joining');

    const { data: existing } = await supabase
      .from('community_members').select('status')
      .eq('community_id', inv.community_id).eq('user_id', uid).maybeSingle();

    if (!existing) {
      const isOpen = inv.community_type === 'open';
      const { error } = await supabase.from('community_members').insert({
        community_id: inv.community_id, user_id: uid, status: isOpen ? 'active' : 'pending',
      });
      if (error) { setErrorMsg(error.message); setStatus('error'); return; }
    }

    setStatus('joined');
    router.replace({ pathname: '/community/[id]', params: { id: inv.slug ?? inv.community_id } } as any);
  }, [router, showAuthModal]);

  useEffect(() => {
    (async () => {
      if (!token) return;
      const { data, error } = await supabase.rpc('resolve_community_invite', { p_token: token });
      const row = (data as ResolvedInvite[] | null)?.[0] ?? null;
      if (error || !row) {
        setInvite(null);
        setStatus('error');
        setErrorMsg('This invite link is invalid or has expired.');
        return;
      }
      setInvite(row);
      join(row);
    })();
  }, [token, join]);

  return (
    <View style={s.root}>
      <Stack.Screen options={{ headerShown: false }} />
      <SafeAreaView edges={['top']} style={s.header}>
        <TouchableOpacity style={s.backBtn} onPress={() => router.replace('/(tabs)/communities' as any)} hitSlop={12}>
          <Ionicons name="close" size={22} color={palette.ink900} />
        </TouchableOpacity>
      </SafeAreaView>

      <View style={s.content}>
        {status === 'error' ? (
          <>
            <View style={s.iconWrap}><Ionicons name="link-outline" size={28} color={palette.gray300} /></View>
            <ThemedText style={s.title}>Invite link not found</ThemedText>
            <ThemedText style={s.sub}>{errorMsg ?? 'This link may have been regenerated by the organiser.'}</ThemedText>
            <TouchableOpacity style={s.btn} onPress={() => router.replace('/(tabs)/communities' as any)}>
              <ThemedText style={s.btnText}>Browse Communities</ThemedText>
            </TouchableOpacity>
          </>
        ) : (
          <>
            <ActivityIndicator size="large" color={palette.blue500} />
            <ThemedText style={s.sub}>
              {invite ? `Joining ${invite.name}…` : 'Loading invite…'}
            </ThemedText>
          </>
        )}
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: palette.white },
  header: { paddingHorizontal: 20, paddingTop: 8 },
  backBtn: { width: 38, height: 38, borderRadius: 19, backgroundColor: palette.surfaceMuted, alignItems: 'center', justifyContent: 'center' },
  content: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 12 },
  iconWrap: { width: 64, height: 64, borderRadius: 32, backgroundColor: palette.surfaceMuted, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  title: { fontSize: 17, fontWeight: '800', color: palette.ink900, textAlign: 'center' },
  sub: { fontSize: 13.5, color: palette.gray450, textAlign: 'center', lineHeight: 19 },
  btn: { marginTop: 12, paddingHorizontal: 24, paddingVertical: 12, borderRadius: radii.pill, backgroundColor: palette.blue500 },
  btnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
});
