-- ACP Intelligence™ — Nutrition Catalogue V1 · PRODUCTION SEED.
-- Generated 2026-09-08T07:27:33.596Z by scripts/generate-nutrition-catalogue-production-sql.ts.
--
-- Source of every nutrient/provenance value: composeMeal()
-- (apps/mobile/lib/nutrition/meal-composer.ts), run against the SAME 120
-- approved meal sources (lib/nutrition/catalogue/index.ts, batches 1-6) and
-- the SAME canonical `foods` evidence already used for the local
-- Production Deployment Package rehearsal. Nothing below was invented or
-- hand-recalculated — every VALUES row is a frozen composeMeal() output.
--
-- SAFE TO RUN VIA THE SUPABASE DASHBOARD SQL EDITOR. Idempotent: upserts on
-- the existing `meals_recipe_reference_unique` constraint
-- (recipe_reference), so re-running this file changes nothing on a second
-- run. Structurally cannot touch a Kenyan (or any other) row, because every
-- Kenyan meal has recipe_reference IS NULL and this statement only ever
-- targets rows by a non-null recipe_reference value.
--
-- Release order (apply once, in this order):
--   1. 20260916000001_meal_catalogue_provenance.sql   (composition_method/recipe_source/recipe_reference columns)
--   2. 20260917000001_canonical_ingredient_expansion.sql (corrected 19 canonical ingredients)
--   3. 20260918000001_meals_recipe_reference_unique.sql  (UNIQUE(recipe_reference) — required for the ON CONFLICT below)
--   4. THIS FILE

BEGIN;

-- ── Preconditions — fail loudly, write nothing, rather than partially deploy ──
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'meals' AND column_name = 'recipe_reference'
  ) THEN
    RAISE EXCEPTION 'Precondition failed: meals.recipe_reference does not exist — apply 20260916000001_meal_catalogue_provenance.sql first.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'meals' AND column_name = 'composition_method'
  ) THEN
    RAISE EXCEPTION 'Precondition failed: meals.composition_method does not exist — apply 20260916000001_meal_catalogue_provenance.sql first.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'meals_recipe_reference_unique'
  ) THEN
    RAISE EXCEPTION 'Precondition failed: meals_recipe_reference_unique constraint does not exist — apply 20260918000001_meals_recipe_reference_unique.sql first.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'meals' AND column_name = 'cuisine'
  ) THEN
    RAISE EXCEPTION 'Precondition failed: meals.cuisine does not exist — base nutrition_hub_schema migration missing.';
  END IF;
END $$;

-- Capture the pre-deploy Kenyan count for the post-deploy comparison below
-- (a session-local TEMP table — persists for the rest of this SQL Editor
-- session so verification query 7 below can read it after COMMIT, and is
-- dropped automatically when the session ends; never a permanent schema
-- change).
CREATE TEMP TABLE _pre_deploy_counts AS
SELECT
  (SELECT count(*) FROM public.meals WHERE recipe_reference IS NULL) AS kenyan_count_before,
  (SELECT count(*) FROM public.meals WHERE recipe_reference IS NOT NULL) AS intl_count_before;

-- ── The 120 approved international meals (upsert by recipe_reference) ──────
INSERT INTO public.meals (
  name, category, cuisine, description, ingredients,
  calories, protein_g, carbs_g, fat_g, fibre_g,
  prep_time_minutes, difficulty, tags, serving_description,
  source, source_type, composition_method, recipe_source, recipe_reference, is_active
)
VALUES
  ('Greek Yoghurt, Oat & Banana Bowl', 'breakfast', 'western', 'Whole-milk Greek yoghurt with rolled oats and fresh banana.', '{"Greek yoghurt, plain, whole milk (170g)","Oats, rolled, dry (40g)","Banana, raw (118g)"}', 422, 21.8, 60.8, 11.5, 7.1, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-01-v1', true),
  ('Nonfat Greek Yoghurt with Apple & Oats', 'breakfast', 'western', 'A lighter yoghurt bowl with rolled oats and fresh apple.', '{"Greek yoghurt, plain, nonfat (170g)","Oats, rolled, dry (30g)","Apple, raw, with skin (150g)"}', 292, 21.7, 47.1, 2.9, 6.6, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-02-v1', true),
  ('Boiled Eggs on Wholegrain Toast', 'breakfast', 'western', 'Two boiled eggs with wholegrain toast, lightly oiled.', '{"Egg, whole, raw (100g)","Wholegrain bread (70g)","Olive oil (5g)"}', 364, 21.3, 30.6, 17, 4.2, NULL, NULL, '{"vegetarian"}', '2 eggs + 2 slices toast', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-03-v1', true),
  ('Scrambled Eggs with Spinach & Cheddar', 'breakfast', 'european', 'Scrambled eggs folded with fresh spinach and cheddar.', '{"Egg, whole, raw (150g)","Spinach, raw (60g)","Cheddar cheese (20g)","Olive oil (8g)"}', 380, 25.1, 3.9, 29.2, 1.3, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-04-v1', true),
  ('Porridge Oats with Milk & Banana', 'breakfast', 'western', 'Classic milk porridge topped with sliced banana.', '{"Oats, rolled, dry (50g)","Semi-skimmed milk (2% fat) (200g)","Banana, raw (100g)"}', 379, 14.3, 66.3, 7.6, 7.7, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-05-v1', true),
  ('Peanut Butter & Banana Wholegrain Toast', 'breakfast', 'western', 'Wholegrain toast with peanut butter and banana slices.', '{"Wholegrain bread (60g)","Peanut butter, smooth (30g)","Banana, raw (100g)"}', 420, 15.2, 55.2, 17.8, 7.7, NULL, NULL, '{"vegetarian"}', '2 slices toast', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-06-v1', true),
  ('Cheese & Tomato Omelette', 'breakfast', 'european', 'A simple three-egg omelette with cheddar and fresh tomato.', '{"Egg, whole, raw (150g)","Cheddar cheese (30g)","Tomato, raw (80g)","Olive oil (8g)"}', 421, 26.4, 5.2, 32.4, 1, NULL, NULL, '{"vegetarian"}', '1 omelette', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-07-v1', true),
  ('Baked Salmon & Avocado on Wholegrain Toast', 'breakfast', 'european', 'A savoury European brunch plate: salmon and avocado on toast with lemon.', '{"Salmon, Atlantic, cooked (80g)","Avocado, raw (60g)","Wholegrain bread (60g)","Lemon, raw (10g)"}', 415, 26.5, 31.7, 20.8, 7.9, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-breakfast-08-v1', true),
  ('Grilled Chicken, Broccoli & Brown Rice Bowl', 'lunch', 'western', 'Roasted chicken breast with steamed broccoli over brown rice.', '{"Chicken breast, roasted, skinless (150g)","Broccoli, raw (100g)","Brown rice, cooked (150g)","Olive oil (10g)"}', 554, 53.5, 45, 17.2, 5, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-01-v1', true),
  ('Tuna, Avocado & Tomato Salad', 'lunch', 'european', 'A cold tuna salad with avocado, tomato and lemon.', '{"Tuna, canned in water, drained (120g)","Avocado, raw (80g)","Tomato, raw (100g)","Lemon, raw (15g)","Olive oil (10g)"}', 342, 26, 12.1, 23.1, 7, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-02-v1', true),
  ('Lentil & Spinach Stew Bowl', 'lunch', 'western', 'A hearty vegetarian lentil stew with spinach and tomato.', '{"Lentils, cooked (200g)","Spinach, raw (60g)","Tomato, raw (80g)","Olive oil (10g)"}', 349, 20.5, 45.6, 11.2, 18.1, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-03-v1', true),
  ('Wholegrain Bread, Cheddar & Apple Plate', 'lunch', 'european', 'A cold ploughman''s-style plate: bread, cheddar, apple and tomato.', '{"Wholegrain bread (60g)","Cheddar cheese (40g)","Apple, raw, with skin (130g)","Tomato, raw (80g)"}', 394, 17.7, 48, 15.8, 7.7, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-04-v1', true),
  ('Kidney Bean, Rice & Cheddar Bowl', 'lunch', 'western', 'A warm vegetarian bowl of kidney beans, brown rice and cheddar.', '{"Kidney beans, cooked (180g)","Brown rice, cooked (150g)","Cheddar cheese (30g)","Tomato, raw (80g)","Olive oil (8g)"}', 619, 27.3, 83.5, 20.5, 16.7, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-05-v1', true),
  ('Salmon & Spinach Salad with Lemon', 'lunch', 'european', 'Cooked salmon over spinach and avocado with a lemon dressing.', '{"Salmon, Atlantic, cooked (130g)","Spinach, raw (80g)","Avocado, raw (50g)","Lemon, raw (15g)","Olive oil (8g)"}', 441, 32.2, 8.6, 31.7, 5.5, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-lunch-06-v1', true),
  ('Baked Salmon with Brown Rice & Broccoli', 'dinner', 'european', 'Cooked salmon with brown rice and steamed broccoli.', '{"Salmon, Atlantic, cooked (150g)","Brown rice, cooked (150g)","Broccoli, raw (100g)","Olive oil (8g)"}', 598, 40.1, 45, 28.4, 5, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-01-v1', true),
  ('Grilled Chicken with Spinach & White Rice', 'dinner', 'western', 'Roasted chicken breast with spinach over white rice.', '{"Chicken breast, roasted, skinless (180g)","Spinach, raw (80g)","White rice, cooked (150g)","Olive oil (8g)"}', 581, 62.2, 45.2, 15.2, 2.4, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-02-v1', true),
  ('Lentil & Kidney Bean Vegetable Stew', 'dinner', 'western', 'A double-legume vegetarian stew with tomato and spinach.', '{"Lentils, cooked (150g)","Kidney beans, cooked (100g)","Tomato, raw (100g)","Spinach, raw (50g)","Olive oil (10g)"}', 419, 24.5, 58.7, 11.5, 21.6, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-03-v1', true),
  ('Tuna, Tomato & White Rice Bowl', 'dinner', 'european', 'Tuna with tomato and lemon over white rice.', '{"Tuna, canned in water, drained (120g)","White rice, cooked (150g)","Tomato, raw (100g)","Lemon, raw (10g)","Olive oil (8g)"}', 390, 28.4, 47.1, 9.8, 2.1, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-04-v1', true),
  ('Gouda, Avocado & Spinach Salad', 'dinner', 'european', 'A cheese-forward vegetarian dinner salad with avocado and spinach.', '{"Gouda cheese (40g)","Avocado, raw (100g)","Spinach, raw (80g)","Lemon, raw (10g)","Olive oil (8g)"}', 394, 14.4, 13.3, 34, 8.7, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-05-v1', true),
  ('Broccoli & Gouda Baked Frittata', 'dinner', 'european', 'A baked egg frittata with broccoli and gouda.', '{"Egg, whole, raw (200g)","Broccoli, raw (80g)","Gouda cheese (30g)","Olive oil (10g)"}', 508, 34.9, 7.4, 37.5, 2.1, NULL, NULL, '{"vegetarian"}', '1 frittata', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch1-dinner-06-v1', true),
  ('Mushroom & Onion Omelette', 'breakfast', 'western', 'A savoury three-egg omelette with white mushroom and onion.', '{"Egg, whole, raw (150g)","Mushroom, white, raw (90g)","Onion, raw (30g)","Olive oil (8g)"}', 317, 22, 6.8, 22.6, 1.4, NULL, NULL, '{"vegetarian"}', '1 omelette', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-breakfast-01-v1', true),
  ('Feta & Cucumber Breakfast Plate', 'breakfast', 'european', 'A simple cold continental plate: feta, cucumber and wholegrain bread.', '{"Feta cheese (40g)","Cucumber, with peel, raw (120g)","Wholegrain bread (60g)","Olive oil (5g)"}', 319, 13.9, 31.5, 15.8, 4.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-breakfast-02-v1', true),
  ('Chicken, Mushroom & Onion Pasta', 'lunch', 'western', 'Cooked pasta with roasted chicken breast, mushroom and onion.', '{"Pasta, cooked (200g)","Chicken breast, roasted, skinless (120g)","Mushroom, white, raw (100g)","Onion, raw (40g)","Olive oil (10g)"}', 640, 52.4, 68.7, 16.5, 5.3, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-01-v1', true),
  ('Tuna, Chickpea & Cucumber Salad', 'lunch', 'european', 'A cold salad of tuna, cooked chickpeas and cucumber with lemon.', '{"Tuna, canned in water, drained (120g)","Chickpeas (garbanzo beans), cooked (150g)","Cucumber, with peel, raw (100g)","Lemon, raw (15g)","Olive oil (10g)"}', 457, 37.4, 46.2, 15.2, 12.3, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-02-v1', true),
  ('Roasted Vegetable & Feta Couscous Bowl', 'lunch', 'western', 'Courgette, bell pepper and aubergine over couscous with feta.', '{"Courgette (zucchini), raw (100g)","Bell pepper (red), raw (100g)","Aubergine (eggplant), raw (100g)","Feta cheese (40g)","Couscous, cooked (150g)","Olive oil (10g)"}', 430, 14.5, 51.4, 19.6, 8.2, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-03-v1', true),
  ('Egg, Potato & Green Bean Salad', 'lunch', 'european', 'A cold potato salad with boiled egg and green beans.', '{"Egg, whole, raw (100g)","Potato, boiled (without skin) (200g)","Green beans, raw (100g)","Olive oil (10g)","Lemon, raw (10g)"}', 437, 17.9, 48.6, 20, 6.6, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-04-v1', true),
  ('Lentil, Carrot & Cauliflower Soup', 'lunch', 'western', 'A warm vegan soup of lentils, carrot, cauliflower and onion.', '{"Lentils, cooked (200g)","Carrot, raw (80g)","Cauliflower, raw (100g)","Onion, raw (30g)","Olive oil (10g)"}', 390, 21, 55.7, 11.3, 20.6, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-05-v1', true),
  ('Wholewheat Pasta with Aubergine & Basil', 'lunch', 'western', 'Wholewheat pasta with aubergine, garlic and fresh basil.', '{"Wholewheat pasta, cooked (200g)","Aubergine (eggplant), raw (120g)","Garlic, raw (6g)","Basil, fresh (5g)","Olive oil (10g)"}', 426, 13.7, 69.3, 13.7, 11.6, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-06-v1', true),
  ('Salmon, Courgette & Lemon Plate', 'lunch', 'european', 'Cooked salmon with courgette and a lemon dressing.', '{"Salmon, Atlantic, cooked (140g)","Courgette (zucchini), raw (120g)","Lemon, raw (15g)","Olive oil (8g)"}', 384, 32.6, 5.1, 25.7, 1.6, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-07-v1', true),
  ('Cheddar, Green Bean & Potato Warm Salad', 'lunch', 'western', 'A warm salad of boiled potato, green beans and cheddar.', '{"Potato, boiled (without skin) (150g)","Green beans, raw (100g)","Cheddar cheese (30g)","Olive oil (8g)"}', 352, 11.3, 38, 18.4, 5.4, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-08-v1', true),
  ('Chicken, Cucumber & Romaine Salad', 'lunch', 'european', 'Roasted chicken breast over romaine, cucumber and bell pepper.', '{"Chicken breast, roasted, skinless (130g)","Lettuce (romaine), raw (80g)","Cucumber, with peel, raw (100g)","Bell pepper (red), raw (60g)","Olive oil (8g)","Lemon, raw (10g)"}', 332, 42.7, 10.8, 13.2, 3.7, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-lunch-09-v1', true),
  ('Roast Chicken with Cauliflower & Carrot', 'dinner', 'western', 'Roasted chicken breast with cauliflower and carrot.', '{"Chicken breast, roasted, skinless (180g)","Cauliflower, raw (120g)","Carrot, raw (80g)","Olive oil (10g)"}', 448, 58.9, 13.6, 17, 4.6, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-01-v1', true),
  ('Baked Aubergine, Courgette & Feta', 'dinner', 'european', 'A baked vegetarian dish of aubergine, courgette, garlic and feta.', '{"Aubergine (eggplant), raw (150g)","Courgette (zucchini), raw (120g)","Feta cheese (40g)","Garlic, raw (6g)","Olive oil (10g)"}', 261, 9, 16.1, 19.3, 5.8, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-02-v1', true),
  ('Salmon with Quinoa & Green Beans', 'dinner', 'european', 'Cooked salmon with quinoa and green beans.', '{"Salmon, Atlantic, cooked (150g)","Quinoa, cooked (150g)","Green beans, raw (100g)","Lemon, raw (10g)","Olive oil (8g)"}', 594, 41.7, 39.9, 29.7, 7.2, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-03-v1', true),
  ('Chickpea, Mushroom & Onion Stew', 'dinner', 'western', 'A hearty vegan stew of chickpeas, mushroom, onion and carrot.', '{"Chickpeas (garbanzo beans), cooked (200g)","Mushroom, white, raw (100g)","Onion, raw (40g)","Garlic, raw (6g)","Carrot, raw (60g)","Olive oil (10g)"}', 488, 22.2, 69.6, 15.7, 18.7, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-04-v1', true),
  ('Potato & Onion Tortilla', 'dinner', 'european', 'A European-style potato and onion omelette (tortilla).', '{"Egg, whole, raw (200g)","Potato, boiled (without skin) (150g)","Onion, raw (50g)","Olive oil (10g)"}', 523, 28.2, 36.1, 29.2, 3.6, NULL, NULL, '{"vegetarian"}', '1 tortilla', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-05-v1', true),
  ('Tuna, Bell Pepper & Rice Bowl', 'dinner', 'european', 'Tuna with bell pepper over brown rice.', '{"Tuna, canned in water, drained (120g)","Bell pepper (red), raw (100g)","Brown rice, cooked (150g)","Olive oil (8g)","Lemon, raw (10g)"}', 387, 28.5, 45.3, 10.9, 4.8, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-06-v1', true),
  ('Kidney Bean, Onion & Bell Pepper Stew', 'dinner', 'western', 'A warm vegan stew of kidney beans, onion, bell pepper and garlic.', '{"Kidney beans, cooked (200g)","Onion, raw (50g)","Bell pepper (red), raw (100g)","Garlic, raw (6g)","Olive oil (10g)"}', 397, 19.3, 58.3, 11.4, 17.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-07-v1', true),
  ('Gouda, Courgette & Potato Bake', 'dinner', 'european', 'A baked vegetarian dish of boiled potato, courgette and gouda.', '{"Potato, boiled (without skin) (180g)","Courgette (zucchini), raw (100g)","Gouda cheese (40g)","Olive oil (8g)"}', 385, 14.3, 40, 19.5, 4.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-08-v1', true),
  ('Chicken, Green Beans & Carrot Traybake', 'dinner', 'western', 'Roasted chicken breast with green beans and carrot.', '{"Chicken breast, roasted, skinless (170g)","Green beans, raw (100g)","Carrot, raw (80g)","Olive oil (8g)"}', 415, 55.3, 14.6, 14.5, 4.9, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch2-dinner-09-v1', true),
  ('Savoury Greek Yoghurt with Cucumber & Garlic', 'breakfast', 'mediterranean', 'A tzatziki-style savoury yoghurt dip with cucumber and garlic, served with bread.', '{"Greek yoghurt, plain, whole milk (170g)","Cucumber, with peel, raw (100g)","Garlic, raw (3g)","Wholegrain bread (40g)","Olive oil (8g)","Lemon, raw (10g)"}', 359, 21.2, 29.4, 18.1, 3.2, NULL, NULL, '{"vegetarian"}', '1 bowl + bread', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-01-v1', true),
  ('Tomato & Pepper Baked Eggs', 'breakfast', 'mediterranean', 'Eggs baked in a tomato, pepper and onion base with garlic.', '{"Egg, whole, raw (150g)","Tomato, raw (100g)","Bell pepper (red), raw (60g)","Onion, raw (40g)","Garlic, raw (3g)","Olive oil (8g)"}', 339, 20.9, 13.3, 22.7, 3.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-02-v1', true),
  ('Feta & Avocado on Wholegrain Toast', 'breakfast', 'mediterranean', 'Wholegrain toast with feta and avocado, finished with lemon.', '{"Feta cheese (40g)","Avocado, raw (80g)","Wholegrain bread (60g)","Lemon, raw (10g)","Olive oil (5g)"}', 432, 14.9, 34.9, 27.5, 9.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-03-v1', true),
  ('Chickpea & Tomato Breakfast Bowl', 'breakfast', 'mediterranean', 'A savoury legume-forward breakfast bowl of chickpeas, tomato and cucumber.', '{"Chickpeas (garbanzo beans), cooked (150g)","Tomato, raw (100g)","Cucumber, with peel, raw (80g)","Olive oil (10g)","Lemon, raw (10g)"}', 367, 14.8, 48.9, 14.2, 13.3, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-04-v1', true),
  ('Tomato, Basil & Cheese Toast', 'breakfast', 'mediterranean', 'Wholegrain toast with cheddar, fresh tomato and basil.', '{"Cheddar cheese (30g)","Tomato, raw (80g)","Basil, fresh (3g)","Wholegrain bread (60g)","Olive oil (5g)"}', 331, 15.1, 29.8, 17.3, 4.6, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-05-v1', true),
  ('Quinoa Breakfast Bowl with Tomato & Cucumber', 'breakfast', 'mediterranean', 'A savoury quinoa breakfast bowl with fresh tomato and cucumber.', '{"Quinoa, cooked (150g)","Tomato, raw (80g)","Cucumber, with peel, raw (80g)","Lemon, raw (10g)","Olive oil (8g)"}', 280, 7.9, 38.9, 11.2, 5.8, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-06-v1', true),
  ('Mushroom & Tomato on Toast', 'breakfast', 'mediterranean', 'Garlicky mushroom and tomato on wholegrain toast.', '{"Mushroom, white, raw (100g)","Tomato, raw (80g)","Garlic, raw (3g)","Wholegrain bread (60g)","Olive oil (8g)"}', 263, 11.5, 33, 10.6, 5.6, NULL, NULL, '{"vegetarian","vegan"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-07-v1', true),
  ('Avocado & Egg Breakfast Plate', 'breakfast', 'mediterranean', 'A simple plate of egg and avocado with wholegrain bread and lemon.', '{"Egg, whole, raw (100g)","Avocado, raw (80g)","Wholegrain bread (40g)","Lemon, raw (10g)","Olive oil (5g)"}', 419, 19.3, 25.6, 27.7, 8, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-breakfast-08-v1', true),
  ('Grilled Chicken with Chickpeas & Cucumber Salad', 'lunch', 'mediterranean', 'Roasted chicken breast with chickpeas and cucumber, dressed with lemon and olive oil.', '{"Chicken breast, roasted, skinless (130g)","Chickpeas (garbanzo beans), cooked (120g)","Cucumber, with peel, raw (100g)","Garlic, raw (3g)","Lemon, raw (15g)","Olive oil (10g)"}', 524, 52, 38.9, 17.9, 10.1, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-01-v1', true),
  ('Salmon with Lentils & Spinach', 'lunch', 'mediterranean', 'Cooked salmon with lentils and spinach, finished with lemon.', '{"Salmon, Atlantic, cooked (140g)","Lentils, cooked (150g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 550, 46.3, 33.3, 26.1, 13.5, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-02-v1', true),
  ('Aubergine & Chickpea Stew', 'lunch', 'mediterranean', 'A vegan stew of aubergine, chickpeas, tomato, onion and garlic.', '{"Aubergine (eggplant), raw (150g)","Chickpeas (garbanzo beans), cooked (150g)","Tomato, raw (100g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (10g)"}', 413, 16.4, 59.2, 14.4, 17.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-03-v1', true),
  ('Cucumber, Tomato & Feta Salad', 'lunch', 'mediterranean', 'A cold salad of cucumber, tomato, bell pepper and feta, dressed with olive oil and lemon.', '{"Cucumber, with peel, raw (120g)","Tomato, raw (120g)","Bell pepper (red), raw (60g)","Feta cheese (40g)","Olive oil (10g)","Lemon, raw (10g)"}', 253, 8.2, 15.1, 19.2, 3.6, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-04-v1', true),
  ('Wholewheat Pasta with Tomato, Garlic & Basil', 'lunch', 'mediterranean', 'A simple wholewheat pasta with fresh tomato, garlic and basil.', '{"Wholewheat pasta, cooked (200g)","Tomato, raw (150g)","Garlic, raw (6g)","Basil, fresh (5g)","Olive oil (10g)"}', 423, 13.8, 68.1, 13.8, 9.8, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-05-v1', true),
  ('Tuna, Kidney Bean & Tomato Salad', 'lunch', 'mediterranean', 'A cold tuna and kidney bean salad with tomato, onion, lemon and olive oil.', '{"Tuna, canned in water, drained (120g)","Kidney beans, cooked (150g)","Tomato, raw (100g)","Onion, raw (30g)","Lemon, raw (10g)","Olive oil (8g)"}', 397, 37.7, 41.8, 10.2, 13.1, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-lunch-06-v1', true),
  ('Baked Chicken with Couscous & Green Beans', 'dinner', 'mediterranean', 'Roasted chicken breast with couscous and green beans.', '{"Chicken breast, roasted, skinless (170g)","Couscous, cooked (150g)","Green beans, raw (100g)","Lemon, raw (10g)","Olive oil (8g)"}', 553, 60.4, 42.7, 14.6, 5.1, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-01-v1', true),
  ('Baked Salmon with Chickpeas & Spinach', 'dinner', 'mediterranean', 'Cooked salmon with chickpeas and spinach, finished with lemon.', '{"Salmon, Atlantic, cooked (150g)","Chickpeas (garbanzo beans), cooked (150g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 642, 48.3, 44.2, 30.7, 13, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-02-v1', true),
  ('Quinoa & Roasted Vegetable Bowl', 'dinner', 'mediterranean', 'A vegan bowl of quinoa with aubergine, bell pepper and courgette.', '{"Quinoa, cooked (150g)","Aubergine (eggplant), raw (100g)","Bell pepper (red), raw (100g)","Courgette (zucchini), raw (100g)","Olive oil (10g)","Lemon, raw (10g)"}', 339, 9.9, 47.9, 13.7, 10.6, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-03-v1', true),
  ('Chickpea, Cauliflower & Tomato Stew', 'dinner', 'mediterranean', 'A vegan stew of chickpeas, cauliflower, tomato, onion and garlic.', '{"Chickpeas (garbanzo beans), cooked (200g)","Cauliflower, raw (150g)","Tomato, raw (100g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (10g)"}', 495, 22.2, 71.6, 15.9, 20.2, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-04-v1', true),
  ('Kidney Bean & Tomato Wholewheat Pasta', 'dinner', 'mediterranean', 'Wholewheat pasta with kidney beans, tomato, onion and garlic.', '{"Wholewheat pasta, cooked (180g)","Kidney beans, cooked (150g)","Tomato, raw (100g)","Onion, raw (30g)","Garlic, raw (5g)","Olive oil (8g)"}', 567, 25.3, 96.7, 12.1, 19.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-05-v1', true),
  ('Grilled Chicken with Aubergine & Tomato', 'dinner', 'mediterranean', 'Roasted chicken breast with aubergine and tomato.', '{"Chicken breast, roasted, skinless (170g)","Aubergine (eggplant), raw (120g)","Tomato, raw (100g)","Garlic, raw (5g)","Olive oil (8g)"}', 407, 55.1, 12.6, 14.5, 4.9, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch3-dinner-06-v1', true),
  ('Boiled Eggs with Cucumber & Tomato', 'breakfast', 'mediterranean', 'Boiled eggs with fresh cucumber and tomato, dressed with lemon and olive oil.', '{"Egg, whole, raw (100g)","Cucumber, with peel, raw (80g)","Tomato, raw (80g)","Olive oil (8g)","Lemon, raw (10g)"}', 243, 13.9, 7.7, 17.8, 1.6, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-breakfast-01-v1', true),
  ('Lentil, Cucumber & Lemon Breakfast Bowl', 'breakfast', 'mediterranean', 'A savoury vegan lentil breakfast bowl with cucumber and lemon.', '{"Lentils, cooked (150g)","Cucumber, with peel, raw (100g)","Lemon, raw (15g)","Olive oil (8g)"}', 264, 14.3, 35.2, 8.7, 12.8, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-breakfast-02-v1', true),
  ('Chicken & Potato Traybake with Green Beans', 'lunch', 'mediterranean', 'Roasted chicken breast with boiled potato and green beans.', '{"Chicken breast, roasted, skinless (150g)","Potato, boiled (without skin) (180g)","Green beans, raw (100g)","Garlic, raw (5g)","Lemon, raw (10g)","Olive oil (10g)"}', 532, 51.9, 45.6, 15.8, 6.3, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-01-v1', true),
  ('Salmon with Couscous & Cucumber', 'lunch', 'mediterranean', 'Cooked salmon with couscous and fresh cucumber.', '{"Salmon, Atlantic, cooked (140g)","Couscous, cooked (150g)","Cucumber, with peel, raw (100g)","Lemon, raw (10g)","Olive oil (8g)"}', 545, 37.4, 39.4, 25.7, 2.9, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-02-v1', true),
  ('Tuna, Courgette & Lemon Bake', 'lunch', 'mediterranean', 'Baked tuna with courgette, garlic and lemon.', '{"Tuna, canned in water, drained (120g)","Courgette (zucchini), raw (120g)","Garlic, raw (5g)","Lemon, raw (15g)","Olive oil (8g)"}', 206, 25.3, 6.8, 9.6, 1.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-03-v1', true),
  ('Baked Eggs with Spinach & Tomato', 'lunch', 'mediterranean', 'Eggs baked with spinach, tomato and garlic.', '{"Egg, whole, raw (150g)","Spinach, raw (60g)","Tomato, raw (80g)","Garlic, raw (3g)","Olive oil (8g)"}', 318, 21.5, 7.4, 22.7, 2.3, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-04-v1', true),
  ('Lentil, Courgette & Tomato Soup', 'lunch', 'mediterranean', 'A warm vegan lentil soup with courgette, tomato and onion.', '{"Lentils, cooked (200g)","Courgette (zucchini), raw (80g)","Tomato, raw (80g)","Onion, raw (30g)","Olive oil (8g)"}', 343, 20, 48.7, 9.2, 18.1, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-05-v1', true),
  ('Kidney Bean & Tomato Soup with Onion', 'lunch', 'mediterranean', 'A warm vegan kidney bean and tomato soup with onion and garlic.', '{"Kidney beans, cooked (200g)","Tomato, raw (100g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (8g)"}', 366, 19, 54.9, 9.3, 16.8, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-06-v1', true),
  ('Grilled Chicken with Cauliflower & Tomato', 'lunch', 'mediterranean', 'Roasted chicken breast with cauliflower and tomato.', '{"Chicken breast, roasted, skinless (150g)","Cauliflower, raw (120g)","Tomato, raw (100g)","Garlic, raw (5g)","Olive oil (8g)"}', 374, 50, 11.5, 13.9, 3.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-07-v1', true),
  ('Pasta with Courgette & Mushroom', 'lunch', 'mediterranean', 'Cooked pasta with courgette, mushroom and garlic.', '{"Pasta, cooked (200g)","Courgette (zucchini), raw (120g)","Mushroom, white, raw (100g)","Garlic, raw (5g)","Olive oil (10g)"}', 454, 16.5, 70.4, 12.6, 5.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-08-v1', true),
  ('Cheddar, Courgette & Tomato Salad', 'lunch', 'mediterranean', 'A cold salad of courgette, tomato and cheddar, dressed with olive oil and lemon.', '{"Cheddar cheese (30g)","Courgette (zucchini), raw (100g)","Tomato, raw (100g)","Olive oil (8g)","Lemon, raw (10g)"}', 230, 9.1, 8.9, 18.5, 2.5, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-lunch-09-v1', true),
  ('Baked Salmon with Potato & Green Beans', 'dinner', 'mediterranean', 'Cooked salmon with boiled potato and green beans.', '{"Salmon, Atlantic, cooked (150g)","Potato, boiled (without skin) (180g)","Green beans, raw (100g)","Lemon, raw (10g)","Olive oil (8g)"}', 568, 38.2, 43.9, 27, 6.2, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-01-v1', true),
  ('Chicken with Rice, Tomato & Onion', 'dinner', 'mediterranean', 'Roasted chicken breast with white rice, tomato and onion.', '{"Chicken breast, roasted, skinless (170g)","White rice, cooked (150g)","Tomato, raw (100g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (8g)"}', 588, 58.4, 51.5, 14.8, 2.6, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-02-v1', true),
  ('Tuna & Cauliflower Bake with Tomato', 'dinner', 'mediterranean', 'Baked tuna with cauliflower and tomato.', '{"Tuna, canned in water, drained (120g)","Cauliflower, raw (150g)","Tomato, raw (100g)","Garlic, raw (5g)","Olive oil (8g)"}', 237, 27.4, 13, 9.8, 4.3, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-03-v1', true),
  ('Aubergine & Lentil Stew', 'dinner', 'mediterranean', 'A vegan stew of aubergine, lentils, tomato, onion and garlic.', '{"Aubergine (eggplant), raw (150g)","Lentils, cooked (150g)","Tomato, raw (100g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (10g)"}', 341, 16.6, 48.3, 11.1, 18.3, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-04-v1', true),
  ('Kidney Bean & Spinach Stew', 'dinner', 'mediterranean', 'A vegan stew of kidney beans, spinach, onion and garlic.', '{"Kidney beans, cooked (200g)","Spinach, raw (80g)","Onion, raw (30g)","Garlic, raw (5g)","Olive oil (10g)"}', 380, 20.3, 53, 11.4, 17.2, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-05-v1', true),
  ('Grilled Chicken with Courgette & Basil', 'dinner', 'mediterranean', 'Roasted chicken breast with courgette, garlic and fresh basil.', '{"Chicken breast, roasted, skinless (170g)","Courgette (zucchini), raw (120g)","Basil, fresh (5g)","Garlic, raw (5g)","Olive oil (8g)"}', 380, 54.7, 5.5, 14.5, 1.4, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-06-v1', true),
  ('Quinoa with Mushroom & Spinach', 'dinner', 'mediterranean', 'A vegan quinoa bowl with mushroom, spinach and garlic.', '{"Quinoa, cooked (150g)","Mushroom, white, raw (100g)","Spinach, raw (60g)","Garlic, raw (5g)","Olive oil (8g)"}', 294, 11.7, 39, 11.5, 6.6, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-07-v1', true),
  ('Salmon with Green Beans & Lemon', 'dinner', 'mediterranean', 'A simple plate of cooked salmon with green beans, garlic and lemon.', '{"Salmon, Atlantic, cooked (150g)","Green beans, raw (120g)","Garlic, raw (5g)","Lemon, raw (15g)","Olive oil (8g)"}', 429, 35.8, 11.4, 26.9, 3.8, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-08-v1', true),
  ('Baked Feta with Tomato & Onion', 'dinner', 'mediterranean', 'Baked feta with tomato, onion and garlic.', '{"Feta cheese (40g)","Tomato, raw (120g)","Onion, raw (40g)","Garlic, raw (5g)","Olive oil (8g)"}', 222, 7.5, 11.6, 16.9, 2.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch4-dinner-09-v1', true),
  ('Peanut Butter, Banana & Oat Bowl', 'breakfast', 'global', 'A milk-based oat bowl with peanut butter and banana.', '{"Oats, rolled, dry (40g)","Peanut butter, smooth (20g)","Banana, raw (100g)","Semi-skimmed milk (2% fat) (100g)"}', 410, 14.1, 59.2, 15.2, 7.6, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-01-v1', true),
  ('Broccoli & Cheddar Baked Eggs', 'breakfast', 'global', 'Eggs baked with broccoli and cheddar.', '{"Egg, whole, raw (150g)","Broccoli, raw (80g)","Cheddar cheese (20g)","Olive oil (8g)"}', 393, 25.7, 7.1, 29.2, 2.1, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-02-v1', true),
  ('Greek Yoghurt with Peanut Butter & Banana', 'breakfast', 'global', 'Nonfat Greek yoghurt with peanut butter and banana, no oats.', '{"Greek yoghurt, plain, nonfat (170g)","Peanut butter, smooth (15g)","Banana, raw (100g)"}', 279, 21.7, 32.3, 8.7, 3.4, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-03-v1', true),
  ('Romaine, Egg & Avocado Breakfast Salad', 'breakfast', 'global', 'A savoury breakfast salad of boiled egg, romaine lettuce and avocado.', '{"Egg, whole, raw (100g)","Lettuce (romaine), raw (60g)","Avocado, raw (60g)","Lemon, raw (10g)","Olive oil (5g)"}', 296, 14.6, 8.7, 23.5, 5.6, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-04-v1', true),
  ('Brown Rice Breakfast Bowl with Banana & Milk', 'breakfast', 'global', 'A rice-based breakfast bowl with banana and milk.', '{"Brown rice, cooked (150g)","Banana, raw (100g)","Semi-skimmed milk (2% fat) (100g)"}', 324, 8.5, 66, 3.8, 5, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-05-v1', true),
  ('Beans & Egg on Toast', 'breakfast', 'global', 'Kidney beans and egg with tomato on wholegrain toast.', '{"Egg, whole, raw (100g)","Kidney beans, cooked (150g)","Tomato, raw (60g)","Wholegrain bread (40g)"}', 445, 31.1, 54.3, 11.8, 14.2, NULL, NULL, '{"vegetarian"}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-06-v1', true),
  ('Carrot & Oat Breakfast Bowl', 'breakfast', 'global', 'A carrot-cake-style oat breakfast bowl with milk.', '{"Oats, rolled, dry (40g)","Carrot, raw (50g)","Semi-skimmed milk (2% fat) (150g)"}', 247, 10.7, 39.1, 5.7, 5.4, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-07-v1', true),
  ('Tuna & Avocado Breakfast Plate', 'breakfast', 'global', 'A light protein breakfast of tuna and avocado on toast.', '{"Tuna, canned in water, drained (80g)","Avocado, raw (80g)","Lemon, raw (10g)","Wholegrain bread (40g)"}', 301, 22.2, 24.8, 13.9, 8, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-breakfast-08-v1', true),
  ('Salmon, Carrot & Brown Rice Bowl', 'lunch', 'global', 'Cooked salmon with carrot and brown rice.', '{"Salmon, Atlantic, cooked (140g)","Carrot, raw (80g)","Brown rice, cooked (150g)","Olive oil (8g)","Lemon, raw (10g)"}', 579, 35.9, 47, 27, 4.9, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-01-v1', true),
  ('Tuna, Romaine & Avocado Salad', 'lunch', 'global', 'A cold tuna salad with romaine lettuce and avocado.', '{"Tuna, canned in water, drained (120g)","Lettuce (romaine), raw (80g)","Avocado, raw (80g)","Lemon, raw (15g)","Olive oil (8g)"}', 320, 26.1, 10.9, 21.2, 7.5, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-02-v1', true),
  ('Chicken, Apple & Cheddar Salad', 'lunch', 'global', 'Roasted chicken breast with apple, cheddar and romaine lettuce.', '{"Chicken breast, roasted, skinless (130g)","Apple, raw, with skin (100g)","Cheddar cheese (20g)","Lettuce (romaine), raw (60g)","Olive oil (8g)","Lemon, raw (10g)"}', 431, 46, 17.4, 19.7, 3.9, NULL, NULL, '{}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-03-v1', true),
  ('Lentil, Carrot & Broccoli Bowl', 'lunch', 'global', 'A vegan bowl of lentils, carrot and broccoli.', '{"Lentils, cooked (200g)","Carrot, raw (80g)","Broccoli, raw (100g)","Olive oil (8g)","Lemon, raw (10g)"}', 372, 21.7, 55.5, 9.4, 20.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-04-v1', true),
  ('Wholewheat Pasta with Broccoli & Cheddar', 'lunch', 'global', 'Wholewheat pasta with broccoli and cheddar, no tomato.', '{"Wholewheat pasta, cooked (200g)","Broccoli, raw (100g)","Cheddar cheese (30g)","Olive oil (8g)"}', 524, 21.7, 67.8, 21.8, 10.4, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-05-v1', true),
  ('Chickpea, Avocado & Romaine Salad', 'lunch', 'global', 'A vegan salad of chickpeas, avocado and romaine lettuce.', '{"Chickpeas (garbanzo beans), cooked (150g)","Avocado, raw (80g)","Lettuce (romaine), raw (60g)","Lemon, raw (15g)","Olive oil (8g)"}', 459, 15.8, 51.3, 23.8, 18.4, NULL, NULL, '{"vegetarian","vegan"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-lunch-06-v1', true),
  ('Chicken, Green Beans & Brown Rice', 'dinner', 'global', 'Roasted chicken breast with green beans and brown rice.', '{"Chicken breast, roasted, skinless (170g)","Green beans, raw (100g)","Brown rice, cooked (150g)","Olive oil (8g)"}', 567, 58.7, 45.3, 15.7, 5.1, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-01-v1', true),
  ('Tuna, Kidney Bean & Avocado Plate', 'dinner', 'global', 'Tuna with kidney beans and avocado, dressed with lemon.', '{"Tuna, canned in water, drained (120g)","Kidney beans, cooked (150g)","Avocado, raw (80g)","Lemon, raw (10g)","Olive oil (8g)"}', 495, 38, 42, 21.7, 16.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-02-v1', true),
  ('Chickpea, Carrot & Broccoli Stew', 'dinner', 'global', 'A vegan stew of chickpeas, carrot, broccoli, onion and garlic.', '{"Chickpeas (garbanzo beans), cooked (200g)","Carrot, raw (80g)","Broccoli, raw (100g)","Onion, raw (30g)","Garlic, raw (5g)","Olive oil (10g)"}', 503, 21.9, 73.6, 15.8, 20.7, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-03-v1', true),
  ('Salmon, Potato & Broccoli Bake', 'dinner', 'global', 'Cooked salmon with boiled potato and broccoli.', '{"Salmon, Atlantic, cooked (150g)","Potato, boiled (without skin) (150g)","Broccoli, raw (100g)","Olive oil (8g)"}', 543, 38.5, 36.7, 27, 5.3, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-04-v1', true),
  ('Kidney Bean, Carrot & Spinach Stew', 'dinner', 'global', 'A vegan stew of kidney beans, carrot, spinach, onion and garlic.', '{"Kidney beans, cooked (200g)","Carrot, raw (80g)","Spinach, raw (60g)","Onion, raw (30g)","Garlic, raw (5g)","Olive oil (10g)"}', 408, 20.4, 59.9, 11.5, 19, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-05-v1', true),
  ('Pasta with Chicken & Broccoli', 'dinner', 'global', 'Cooked pasta with roasted chicken breast and broccoli.', '{"Pasta, cooked (200g)","Chicken breast, roasted, skinless (120g)","Broccoli, raw (100g)","Olive oil (8g)"}', 619, 51.6, 68.4, 14.5, 6.2, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch5-dinner-06-v1', true),
  ('Chicken & Avocado Breakfast Plate', 'breakfast', 'global', 'A protein-forward breakfast of roasted chicken breast and avocado on toast.', '{"Chicken breast, roasted, skinless (100g)","Avocado, raw (60g)","Wholegrain bread (40g)","Lemon, raw (10g)"}', 365, 37.3, 23.1, 13.8, 6.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-breakfast-01-v1', true),
  ('Quinoa & Salmon Breakfast Bowl', 'breakfast', 'global', 'A savoury fish-and-grain breakfast bowl, no bread or dairy.', '{"Quinoa, cooked (100g)","Salmon, Atlantic, cooked (60g)","Lemon, raw (10g)","Olive oil (5g)"}', 291, 17.8, 22.2, 14.4, 3.1, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-breakfast-02-v1', true),
  ('Quinoa, Chicken & Spinach Bowl', 'lunch', 'global', 'Quinoa never previously paired with chicken — a protein-grain-greens bowl.', '{"Quinoa, cooked (150g)","Chicken breast, roasted, skinless (120g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 465, 45.7, 35.1, 15.4, 5.8, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-01-v1', true),
  ('Egg, Avocado & Tomato Salad', 'lunch', 'global', 'A cold egg salad with avocado and tomato — no potato or spinach.', '{"Egg, whole, raw (100g)","Avocado, raw (80g)","Tomato, raw (80g)","Lemon, raw (10g)","Olive oil (5g)"}', 333, 15, 11.6, 26.4, 6.6, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-02-v1', true),
  ('Gouda, Apple & Romaine Salad', 'lunch', 'global', 'Gouda has never appeared at lunch before — a cheese-and-fruit salad, no meat.', '{"Gouda cheese (30g)","Apple, raw, with skin (100g)","Lettuce (romaine), raw (60g)","Lemon, raw (10g)","Olive oil (5g)"}', 216, 8.6, 17.4, 13.6, 3.9, NULL, NULL, '{"vegetarian"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-03-v1', true),
  ('Couscous, Egg & Spinach Bowl', 'lunch', 'global', 'Couscous has never previously been paired with egg.', '{"Couscous, cooked (150g)","Egg, whole, raw (100g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 398, 20.1, 38.7, 18, 3.7, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-04-v1', true),
  ('White Rice, Kidney Bean & Carrot Bowl', 'lunch', 'global', 'White rice has never previously appeared at lunch.', '{"White rice, cooked (150g)","Kidney beans, cooked (150g)","Carrot, raw (80g)","Olive oil (8g)"}', 489, 17.8, 84.1, 9.4, 13.9, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-05-v1', true),
  ('Cauliflower & Chickpea Salad', 'lunch', 'global', 'A cold, raw cauliflower salad — every existing cauliflower dish in the catalogue is warm.', '{"Cauliflower, raw (150g)","Chickpeas (garbanzo beans), cooked (150g)","Lemon, raw (15g)","Olive oil (8g)"}', 359, 16.3, 50, 12.4, 14.8, NULL, NULL, '{"vegetarian","vegan"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-06-v1', true),
  ('Brown Rice, Chickpea & Spinach Bowl', 'lunch', 'global', 'A vegan legume-and-grain bowl.', '{"Brown rice, cooked (150g)","Chickpeas (garbanzo beans), cooked (150g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 518, 19.2, 82.6, 13.6, 15.4, NULL, NULL, '{"vegetarian","vegan"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-07-v1', true),
  ('Salmon, White Rice & Spinach Bowl', 'lunch', 'global', 'Salmon has never previously been paired with white rice.', '{"Salmon, Atlantic, cooked (140g)","White rice, cooked (150g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 571, 36.8, 45.4, 26, 2.2, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-08-v1', true),
  ('Wholewheat Pasta with Chicken & Spinach', 'lunch', 'global', 'The first protein-forward (meat) wholewheat pasta dish in the catalogue.', '{"Wholewheat pasta, cooked (200g)","Chicken breast, roasted, skinless (120g)","Spinach, raw (60g)","Olive oil (8g)"}', 581, 50.9, 62.3, 15.9, 9.1, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-lunch-09-v1', true),
  ('Yoghurt-Marinated Chicken with Spinach', 'dinner', 'global', 'Yoghurt used as a savoury marinade/sauce — every other yoghurt dish in the catalogue is a sweet breakfast bowl.', '{"Chicken breast, roasted, skinless (150g)","Greek yoghurt, plain, whole milk (100g)","Spinach, raw (60g)","Lemon, raw (10g)","Garlic, raw (5g)"}', 369, 57.7, 8.7, 10.6, 1.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-01-v1', true),
  ('Egg, Potato & Spinach Bake', 'dinner', 'global', 'The first non-European egg dinner in the catalogue.', '{"Egg, whole, raw (200g)","Potato, boiled (without skin) (150g)","Spinach, raw (60g)","Olive oil (8g)"}', 500, 29.4, 33.6, 27.4, 4, NULL, NULL, '{"vegetarian"}', '1 bake', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-02-v1', true),
  ('Couscous, Tuna & Tomato Bowl', 'dinner', 'global', 'Tuna has never previously been paired with couscous.', '{"Couscous, cooked (150g)","Tuna, canned in water, drained (120g)","Tomato, raw (80g)","Lemon, raw (10g)","Olive oil (8g)"}', 359, 29.8, 38.9, 9.6, 3.3, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-03-v1', true),
  ('Apple, Chicken & Spinach Bake', 'dinner', 'global', 'Apple has never previously appeared in a warm dinner dish.', '{"Chicken breast, roasted, skinless (150g)","Apple, raw, with skin (100g)","Spinach, raw (60g)","Olive oil (8g)"}', 384, 48.5, 16, 13.8, 3.7, NULL, NULL, '{}', '1 plate', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-04-v1', true),
  ('Cauliflower, Kidney Bean & Cheddar Bake', 'dinner', 'global', 'A new cauliflower/legume/cheese combination not tried elsewhere.', '{"Cauliflower, raw (200g)","Kidney beans, cooked (100g)","Cheddar cheese (30g)","Olive oil (8g)"}', 369, 19.4, 33.8, 19.1, 11.4, NULL, NULL, '{"vegetarian"}', '1 bake', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-05-v1', true),
  ('White Rice, Egg & Broccoli Bowl', 'dinner', 'global', 'White rice has never previously appeared at dinner outside a fish/chicken bowl, and never with egg.', '{"White rice, cooked (150g)","Egg, whole, raw (100g)","Broccoli, raw (100g)","Olive oil (8g)"}', 443, 19.4, 49.6, 18.3, 3.2, NULL, NULL, '{"vegetarian"}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-06-v1', true),
  ('Wholewheat Pasta with Salmon & Spinach', 'dinner', 'global', 'The first fish wholewheat-pasta dish in the catalogue.', '{"Wholewheat pasta, cooked (180g)","Salmon, Atlantic, cooked (130g)","Spinach, raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 623, 41.3, 57.2, 27.4, 8.6, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-07-v1', true),
  ('Kidney Bean, Apple & Romaine Salad', 'dinner', 'global', 'The first cold kidney-bean salad in the catalogue — every other kidney-bean dish is a warm stew or bowl.', '{"Kidney beans, cooked (150g)","Apple, raw, with skin (80g)","Lettuce (romaine), raw (60g)","Lemon, raw (10g)","Olive oil (8g)"}', 316, 14.1, 48.2, 9.1, 14.6, NULL, NULL, '{"vegetarian","vegan"}', '1 salad', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-08-v1', true),
  ('Quinoa, Tuna & Bell Pepper Bowl', 'dinner', 'global', 'Quinoa has never previously been paired with tuna.', '{"Quinoa, cooked (150g)","Tuna, canned in water, drained (120g)","Bell pepper (red), raw (80g)","Lemon, raw (10g)","Olive oil (8g)"}', 378, 30.8, 37.7, 12.3, 6.2, NULL, NULL, '{}', '1 bowl', 'ACP curated recipe (FoodData Central-grounded ingredients)', 'acp_curated', 'standard_recipe_estimated', 'ACP standardized recipe (ingredient nutrients: USDA FoodData Central via ACP foods catalogue; recipe ratios ACP-composed for a plausible single-person serving)', 'acp-recipe:batch6-dinner-09-v1', true)
ON CONFLICT (recipe_reference) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, cuisine = EXCLUDED.cuisine,
  description = EXCLUDED.description, ingredients = EXCLUDED.ingredients,
  calories = EXCLUDED.calories, protein_g = EXCLUDED.protein_g, carbs_g = EXCLUDED.carbs_g,
  fat_g = EXCLUDED.fat_g, fibre_g = EXCLUDED.fibre_g,
  prep_time_minutes = EXCLUDED.prep_time_minutes, difficulty = EXCLUDED.difficulty,
  tags = EXCLUDED.tags, serving_description = EXCLUDED.serving_description,
  source = EXCLUDED.source, source_type = EXCLUDED.source_type,
  composition_method = EXCLUDED.composition_method, recipe_source = EXCLUDED.recipe_source,
  is_active = EXCLUDED.is_active;

-- ── Postcondition — abort the whole transaction if this write didn't land
--    exactly 120 international rows (never partially deploy) ───────────────
DO $$
DECLARE
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count FROM public.meals WHERE recipe_reference IS NOT NULL;
  IF v_count <> 120 THEN
    RAISE EXCEPTION 'Postcondition failed: expected exactly 120 international (recipe_reference IS NOT NULL) meals after upsert, found %. Rolling back.', v_count;
  END IF;
END $$;

COMMIT;

-- ════════════════════════════════════════════════════════════════════════
-- VERIFICATION QUERIES — run after COMMIT above (read-only)
-- ════════════════════════════════════════════════════════════════════════

-- 1. Exactly 120 Lana Catalogue V1 meals.
SELECT count(*) AS international_meal_count FROM public.meals WHERE recipe_reference IS NOT NULL;
-- expect: 120

-- 2. Cuisine group breakdown: European/Western = 40, Mediterranean = 40, Global = 40.
SELECT
  CASE WHEN cuisine IN ('western','european') THEN 'european_western' ELSE cuisine END AS cuisine_group,
  count(*)
FROM public.meals WHERE recipe_reference IS NOT NULL
GROUP BY 1 ORDER BY 1;
-- expect: european_western=40, mediterranean=40, global=40

-- 3. Category ("occasion") breakdown: 30 breakfast / 45 lunch / 45 dinner.
SELECT category, count(*) FROM public.meals
WHERE recipe_reference IS NOT NULL GROUP BY category ORDER BY category;
-- expect: breakfast=30, lunch=45, dinner=45

-- 4. Zero duplicate recipe_reference anywhere in meals.
SELECT recipe_reference, count(*) FROM public.meals
WHERE recipe_reference IS NOT NULL GROUP BY recipe_reference HAVING count(*) > 1;
-- expect: 0 rows

-- 5. Complete provenance on every new catalogue row.
SELECT count(*) AS rows_missing_provenance FROM public.meals
WHERE recipe_reference IS NOT NULL
  AND (composition_method IS NULL OR recipe_source IS NULL OR recipe_reference IS NULL);
-- expect: 0

-- 6. No null core macros on new rows (fibre may legitimately be NULL — UNKNOWN ≠ ZERO).
SELECT name, recipe_reference FROM public.meals
WHERE recipe_reference IS NOT NULL
  AND (calories IS NULL OR protein_g IS NULL OR carbs_g IS NULL OR fat_g IS NULL);
-- expect: 0 rows

-- 7. Kenyan meal count unchanged before vs after this deploy.
SELECT
  p.kenyan_count_before,
  (SELECT count(*) FROM public.meals WHERE recipe_reference IS NULL) AS kenyan_count_after,
  p.intl_count_before,
  (SELECT count(*) FROM public.meals WHERE recipe_reference IS NOT NULL) AS intl_count_after
FROM _pre_deploy_counts p;
-- expect: kenyan_count_before = kenyan_count_after; intl_count_after = 120
-- NOTE: _pre_deploy_counts is a TEMP table scoped to this SQL Editor
-- session/transaction — run this query in the SAME session as the block
-- above, before the session ends, or re-derive kenyan_count_before from
-- your own separately-recorded pre-deploy count if running it later.
