"use client";

import { useEffect, useState, use, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createBrowserClient } from "@supabase/ssr";

const supabase = createBrowserClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

interface ResolvedInvite {
  community_id: string;
  name: string;
  slug: string | null;
  community_type: "open" | "approval_required";
}

export default function CommunityJoinPage({ params }: { params: Promise<{ slug: string; token: string }> }) {
  const { slug, token } = use(params);
  const router = useRouter();

  const [invite, setInvite] = useState<ResolvedInvite | null>(null);
  const [status, setStatus] = useState<"resolving" | "joining" | "signin" | "error">("resolving");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const join = useCallback(async (inv: ResolvedInvite) => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { setStatus("signin"); return; }

    setStatus("joining");

    const { data: existing } = await supabase
      .from("community_members").select("status")
      .eq("community_id", inv.community_id).eq("user_id", user.id).maybeSingle();

    if (!existing) {
      const isOpen = inv.community_type === "open";
      const { error } = await supabase.from("community_members").insert({
        community_id: inv.community_id, user_id: user.id, status: isOpen ? "active" : "pending",
      });
      if (error) { setErrorMsg(error.message); setStatus("error"); return; }
    }

    router.replace(`/community/${inv.slug ?? inv.community_id}`);
  }, [router]);

  useEffect(() => {
    (async () => {
      const { data, error } = await supabase.rpc("resolve_community_invite", { p_token: token });
      const row = (data as ResolvedInvite[] | null)?.[0] ?? null;
      if (error || !row) {
        setStatus("error");
        setErrorMsg("This invite link is invalid or has been regenerated by the organiser.");
        return;
      }
      setInvite(row);
      join(row);
    })();
  }, [token, join]);

  return (
    <div className="max-w-md mx-auto px-6 py-24 text-center">
      {status === "error" ? (
        <>
          <h1 className="text-xl font-bold text-gray-900 mb-2">Invite link not found</h1>
          <p className="text-sm text-gray-500 mb-6">{errorMsg}</p>
          <Link href="/community" className="inline-block px-5 py-2.5 text-sm font-semibold rounded-xl bg-black text-white hover:bg-gray-800 transition">
            Browse Communities
          </Link>
        </>
      ) : status === "signin" ? (
        <>
          <h1 className="text-xl font-bold text-gray-900 mb-2">
            {invite ? `You've been invited to join ${invite.name}` : "Sign in to continue"}
          </h1>
          <p className="text-sm text-gray-500 mb-6">Sign in or create an account to join this community.</p>
          <a
            href={`/login?redirect=${encodeURIComponent(`/community/join/${slug}/${token}`)}`}
            className="inline-block px-5 py-2.5 text-sm font-semibold rounded-xl bg-black text-white hover:bg-gray-800 transition"
          >
            Sign in
          </a>
        </>
      ) : (
        <>
          <div className="w-8 h-8 border-2 border-gray-200 border-t-gray-900 rounded-full animate-spin mx-auto mb-4" />
          <p className="text-sm text-gray-500">{invite ? `Joining ${invite.name}…` : "Loading invite…"}</p>
        </>
      )}
    </div>
  );
}
